version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/fibonacci
permissions:
  - object: /home/ubuntu/fibonacci
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
